baseURL = "https://miles.land/"
languageCode = "en-us"
title = "R. Miles McCain"

[taxonomies]
tag = "tags"

[[menu.main]]
name = "Portfolio"
url = "/portfolio/"
weight = 0

[[menu.main]]
name = "Micros"
url = "/micro/"
weight = 1

[[menu.main]]
name = "Errata"
url = "/errata/"
weight = 2

[[menu.main]]
name = "Cool"
url = "/cool/"
weight = 3

[[menu.main]]
name = "Posts"
url = "/post/"
weight = 4