baseURL = "/"
languageCode = "en-us"
title = "R. Miles McCain"
pygmentsUseClasses = true

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
tag = "tags"

[[menu.main]]
name = "Portfolio"
url = "/portfolio/"
weight = 1
[menu.main.params]
    style = "critical"

[[menu.main]]
name = "Micros"
url = "/micros/"
weight = 2
[menu.main.params]
    style = "warning"

[[menu.main]]
name = "Cool"
url = "/cool/"
weight = 3
[menu.main.params]
    style = "positive"

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 4
[menu.main.params]
    style = "info"

[[menu.main]]
name = "Letter"
url = "/letter/"
weight = 5
[menu.main.params]
    style = "urge"