baseURL = "/"
languageCode = "en-us"
title = "Daniel Longo"
pygmentsUseClasses = true

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
tag = "tags"

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 1
[menu.main.params]
    style = "critical"

[[menu.main]]
name = "Experience"
url = "/experience/"
weight = 2
[menu.main.params]
    style = "info"

[[menu.main]]
name = "Letter"
url = "/letter/"
weight = 4
[menu.main.params]
    style = "positive"

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 3
[menu.main.params]
    style = "warning"
