[build]
publish = "public"
command = "hugo --minify --gc"

[context.hugo.environment]
HUGO_VERSION = "0.73"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.production.environment]
HUGO_VERSION = "0.73"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"