backend:
  name: git-gateway
  branch: master
media_folder: "/static/media"
public_folder: "/media"
collections:
  - name: "micros"
    label: "Micro"
    create: true
    folder: "content/micros/"
    title: "micros"
    identifier_field: "body"
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{second}}"
    fields:
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: 'Body', name: 'body', widget: 'markdown' }
