backend:
  name: git-gateway
  branch: master
media_folder: "/static/media" # Media files will be stored in the repo under static/images/uploads
public_folder: "/media"
collections:
  - name: "micros"
    label: "Mirco"
    folder: "content/micros/"
    fields:
      - { label: "Date", name: "date" }
