backend:
  name: git-gateway
  branch: master
media_folder: "/static/media" # Media files will be stored in the repo under static/images/uploads
public_folder: "/media"
collections:
  - name: "micros"
    label: "Mirco"
    create: true
    folder: "content/micros/"
    title: "micros"
    identifier_field: "body"
    slug: "{{slug}}"
    fields:
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: 'Body', name: 'body', widget: 'markdown' }
